name: feed

on:
  push:
    paths:
      - '**.php'
      - '**.md'
  pull_request:
    paths:
      - '**.php'
      - '**.md'

jobs:
  feed:
    name: feed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}

      - name: Run composer install
        run: composer install --no-interaction --prefer-dist --ansi -v

      - name: Run feed
        run: ./favorite-link feed:generate --ansi -v

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Update feed'
          file_pattern: '**.{atom,rss}'
