name: lint markdown

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/**.yml'
      - '.github/**.yaml'
      - '**.md'
      - '.*rc'
  pull_request:
    paths:
      - '.github/**.yml'
      - '.github/**.yaml'
      - '**.md'
      - '.*rc'

jobs:
  lint-markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set node version
        uses: actions/setup-node@v4

      - name: Install lint-md
        run: npm install @lint-md/cli -g

      - name: Install zhlint
        run: npm install zhlint -g

      - name: Lint markdown
        run: lint-md 'README.md' --config=.lintmdrc --threads --fix

      - name: Lint zh_CN
        run: zhlint 'README.md' --fix

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_options: '--no-verify'
          commit_message: Fix README.md
          file_pattern: 'README.md'
